sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
script:
- pep8 uw_upass/ --exclude=uw_upass/tests
- coverage run --source=uw_upass uw_upass/test.py -v
after_script:
- coveralls
